project:
  type: book
  output-dir: docs
book:
  title: GRAPH Winterakademie
  subtitle: Quantitative Datenanalyse für Fortgeschrittene
  author: Samuel Merk
  chapters:
  - index.qmd
  - regression.qmd
  - cfa.qmd
  - longitudinal_measurement_invariance.qmd
  - cross_lagged_panel_models.qmd
  - latent_change_score_models.qmd
  - references.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    fontsize: .8em
lang: de
lightbox: false
